### ISSUE TITLE
Dataset Issues

### ISSUE THREAD

**Issue by LucasChenLC** [josephkamel/F2MD#1]
Hello Sir, we are trying to use your framework to verify our ML model. However, we met some problems with your framework. Hope you can help us address it.

First off, we read the source code of the offline training session, which is in the MLMain.py. There are some specific types of files confuse us, the .bsm and .lbsm one. We have read your paper and README file. Yet we can't tell the function and the structure of these files. If you can tell us the origin of the file, that is even better.

Secondly, we wonder whether the data form in the test process correspond with your VeRiMe Extension.

**Comment by qiy360** [comment]
![12](https://user-images.githubusercontent.com/71126686/121508764-8be50500-ca18-11eb-814b-631304ac49b4.png)

can you resolve the problem?

**Comment by natalie-v2x** [comment]
I have met the error before. You simply have to install the exact version of OMNET and SUMO as what the README read. Otherwise I'm afraid the F2MD project needs to be refactored, which is not an easy job.

**Comment by natalie-v2x** [comment]
In addition, I am wondering if the F2MD comes with implementation of some machine learning models as what the variable `savePath` in MLMain.py specifies because I ran into an error saying `files do not exist` at the line 264 in MLMain.py. Would you please kindly provide some feedback on this issue? Thanks.

**Comment by qiy360** [comment]
> I have met the error before. You simply have to install the exact version of OMNET and SUMO as what the README read. Otherwise I'm afraid the F2MD project needs to be refactored, which is not an easy job.

I had installed  Sumo 1.5.0 and OMNeT++ 5.6.1,   it's right version?
Then I hardcode some parameters,   cmd env can work and   Qt env can't work

**Comment by josephkamel** [comment]
F2MD includes a [machine-learning-server](https://github.com/josephkamel/F2MD/tree/master/machine-learning-server).
However, no trained ML models are provided.

The steps to using the server would be:
1. collect data sample from the simulator using the dataset parameter in omnetpp.ini:
```
*.node[*].appl.writeListBsmsV1 = true).
```
2. train the server, this process is not that simple and requires some technical knowledge, especially in python. Hint: start by modifying [MLMain.py](https://github.com/josephkamel/F2MD/tree/master/machine-learning-server/MLMain.py) variables to:
```
RTtrain = True     #Look where this variable is mentioned
RTcollectData = False
RTpredict = False
```
3. Once the model is trained, it can be tested live using a simulation, the server can be launched using [launchMLServer](https://github.com/josephkamel/F2MD/tree/master/machine-learning-server/launchMLServer) and called in the simulation by setting the detection parameter in omnetpp.ini:
```
*.node[*].appl.appTypeV1 = 5
```

**Comment by Izdhar** [comment]
I am new in ML, and I work on F2MD, i train the model , I have some Q:
1-where in F2MD using OMNET, SUMO?
2- if I must import data from VeReMi or not?
3- i write the first step, than, i edit on MLMain.py, than Run F2MD ?? OR not
please help me
