### ISSUE TITLE
Not issues but sincerely ask for help

### ISSUE THREAD

**Issue by chenye202558** [josephkamel/F2MD#4]
Dear author：
          I am a PhD candidate in China, Ye Chen. I have carefully studied the F2MD framework you provided. Its functions are very powerful and comprehensive, which is very helpful for my research and study. When I am trying to modify some of the content, I have encountered huge difficulties, especially the complex code structure of Veins in OMNET++, so I would like to ask you for help if there are any related courses or documents that can help me learn related content. I sincerely look forward to your reply! Thanks!

**Comment by YuTao995** [comment]
>
您好，我想向您请教一下怎么运行这个框架，折腾半天一直运行不了。谢谢大佬

**Comment by chenye202558** [comment]
您好，F2MD这个框架最难的是安装完整的运行环境，根据我的经验，从github这个项目上下载installF2MD这个文件，放到linux系统中自定义的目录，运行文件会自动安装，如果安装进度特别慢，建议科学上网再试试。直接从github上下载的项目文件是不完整的，无法运行。如果installF2MD安装成功，按照作者自己写的README，是可以运行的，安装结束后先看看omnet和sumo这两个基础仿真平台能不能正常运行，如果OK再按照作者给出的说明运行程序。installF2MD安装过程可能需要反复尝试，然后我也不是大佬哈哈，我之前是VM+虚拟机ubuntu安装，很慢很卡，后来我直接刷了一台笔记本ubuntu，安装会快一些。希望我的经验会对您有一些帮助，原作者Joseph Kamel应该已经毕业了，应该是不会提供任何进一步的帮助了，可以看到他很久都没有登陆了。
----- 原始邮件 -----
发件人：YuTao995 ***@***.***>
收件人：josephkamel/F2MD ***@***.***>
抄送人：Chen ye ***@***.***>,  State change ***@***.***>
主题：Re: [josephkamel/F2MD] Not issues but sincerely ask for help (Issue #4)
日期：2022年04月25日 15点28分







您好，我想向您请教一下怎么运行这个框架，折腾半天一直运行不了。谢谢大佬



&mdash;

**Comment by YuTao995** [comment]
万分感谢赐教，对我受益匪浅，不知道能否留个联系方式？不会总是打扰你的，再次感谢。
