### ISSUE TITLE
VM password 

### ISSUE THREAD

**Issue by tarzs** [josephkamel/F2MD#8]
Hi I am trying to figure out the password for using the VM provided in the attached link. I wonder if you could please suggest the password?

Kind regards 

<img width="1388" alt="Screenshot 2023-05-09 at 21 05 13" src="https://github.com/josephkamel/F2MD/assets/46527187/c003635f-f952-4af6-9d83-d8c178fdf54e">

**Comment by Musdora** [comment]
Can you download the virtual machine in the link? I can't open the link here

**Comment by Enough7** [comment]
@tarzs did you find out the password?
